on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@ccd2f9f4a24f34ea1165a717af125260d93bb5c1  # v2.6.1
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
